language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - sys-img-x86-android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
   - ./gradlew build connectedCheck